ARG UBUNTU_VER
FROM ubuntu:${UBUNTU_VER}
RUN set -eux;\
 apt-get update; env DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
 aspcud \
 autoconf \
 automake \
 build-essential \
 bzip2 \
 ca-certificates \
 cmake \
 curl \
 git-core \
 libc6-dev \
 ocaml-nox \
 pkg-config \
 sudo \
 unzip \
 xz-utils \
 ;\
 env DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y software-properties-common;\
 add-apt-repository ppa:avsm/ppa;\
 apt install --no-install-recommends -y opam;\
 apt remove --auto-remove -y software-properties-common;\
 apt-get clean;rm -rf /var/lib/apt/lists/*;\
 echo bubblewrap; \
 echo DONE

ARG USERID
ARG GROUPID
ARG USERNAME
ARG UI
RUN \
  set -eux; \
  groupadd -g $GROUPID $USERNAME; \
  useradd -m -u $USERID -g $GROUPID $USERNAME; \
  usermod -aG sudo $USERNAME; \
  echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers; \
  echo $USERNAME >/root/USERNAME; \
  chgrp $GROUPID /root; \
  chmod g+rx /root; \
  mkdir /src;\
  chown $USERNAME /src;\
  if [ _${UI} != _n ]; then\
    apt-get update; env DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
      elpa-auto-complete \
      elpa-evil \
      emacs \
      less \
      ocaml-mode \
      vim-nox \
      xterm \
  ; fi ; \
  echo DONE

ARG UBUNTU_VER
USER ${USERNAME}
RUN set -exu;\
  cd src;\
  which ocaml;ocaml -version;\
  which opam;opam --version;\
  if [ _${UBUNTU_VER} = _16.04 ]; then \
   curl -o /tmp/install.sh -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh;\
   (echo;)|sh /tmp/install.sh;\
   which opam;opam --version;\
   rm /tmp/*;fi;\
  opam init --disable-sandboxing -a;\
  eval `opam config env`;\
  which ocaml;ocaml -version;\
  opam install -y dune;\
  if [ _${UI} != _n ]; then \
    opam install -y tuareg; \
    opam install -y merlin; \
    mkdir -p ~/.emacs.d;\
    echo "(require 'evil)" >>~/.emacs.d/init.el;\
    echo "(evil-mode 1)" >>~/.emacs.d/init.el;\
    echo '(load "/home/'${USERNAME}'/.opam/default/share/emacs/site-lisp/tuareg-site-file")' >>~/.emacs.d/init.el;\
    printf \
 '(let ((opam-share (ignore-errors (car (process-lines "opam" "config" "var" "share")))))\n\
   (when (and opam-share (file-directory-p opam-share))\n\
    ;; Register Merlin\n\
    (add-to-list '\''load-path (expand-file-name "emacs/site-lisp" opam-share))\n\
    (autoload '\''merlin-mode "merlin" nil t nil)\n\
    ;; Automatically start it in OCaml buffers\n\
    (add-hook '\''tuareg-mode-hook '\''merlin-mode t)\n\
    (add-hook '\''caml-mode-hook '\''merlin-mode t)\n\
    ;; Use opam switch to lookup ocamlmerlin binary\n\
    (setq merlin-command '\''opam)))\n'>>~/.emacs.d/init.el;\
  fi; \
  echo DONE
RUN set -exu;\
  sudo apt-get update; sudo env DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y libfuse-dev;\
  sudo apt-get clean;sudo rm -rf /var/lib/apt/lists/*;\
  cd src;\
  git clone https://github.com/astrada/ocamlfuse.git;\
  cd ocamlfuse;\
  eval `opam config env`;\
  opam install --deps-only -y .;\
  eval `opam config env`;\
  which ocaml;ocaml -version;\
  echo DONE
RUN set -exu;\
  cd src/ocamlfuse;\
  opam install -y .;\
  echo DONE
RUN set -eux;\
  sudo apt-get update; sudo env DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y fuse linux-tools-common;\
  sudo apt-get env DEBIAN_FRONTEND=noninteractive install --no-install-recommends -y linux-tools-$(uname -r)||true; \
  sudo apt-get clean;sudo rm -rf /var/lib/apt/lists/*;\
  echo DONE
